version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_IMAGE: uilianries/conanmsvc15
  DOCKER_CONTAINER: conanmsvc15
  DOCKER_USERNAME:
    secure: f4lJhL/Ls1T9CB7FmhoYQg==
  DOCKER_PASSWORD:
    secure: CWUJzILKsJR6Oz2aG8YxDZeWJx/vOoUwNc1msQuvqh0=

install:
  - docker version

before_build:
  - docker login -u="%DOCKER_USERNAME%" -p="%DOCKER_PASSWORD%"

build_script:
  - docker build -t %DOCKER_IMAGE% .
  - docker images

test_script:
- docker run -t -d --name %DOCKER_CONTAINER% %DOCKER_IMAGE%
- docker exec %DOCKER_CONTAINER% cl.exe
- docker exec %DOCKER_CONTAINER% pip install -U conan_package_tools
- docker exec %DOCKER_CONTAINER% pip install -U conan
- docker exec %DOCKER_CONTAINER% conan profile new default --detect
- docker exec %DOCKER_CONTAINER% conan profile show default
- docker exec %DOCKER_CONTAINER% conan install bzip2/1.0.6@conan/stable -s arch=x86_64 -s compiler="Visual Studio" -s compiler.version=15 -s compiler.runtime=MD --build
- docker exec %DOCKER_CONTAINER% conan install bzip2/1.0.6@conan/stable -s arch=x86 -s compiler="Visual Studio" -s compiler.version=15 -s compiler.runtime=MD --build
- docker exec %DOCKER_CONTAINER% conan install gtest/1.8.1@bincrafters/stable -s arch=x86_64 -s compiler="Visual Studio" -s compiler.version=15 -s compiler.runtime=MD --build
- docker exec %DOCKER_CONTAINER% conan install gtest/1.8.1@bincrafters/stable -s arch=x86 -s compiler="Visual Studio" -s compiler.version=15 -s compiler.runtime=MD --build
- docker stop %DOCKER_CONTAINER%
- docker rm %DOCKER_CONTAINER%

deploy_script:
  - docker push %DOCKER_IMAGE%
