version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_IMAGE: uilianries/conanmsvc14
  DOCKER_USERNAME:
    secure: f4lJhL/Ls1T9CB7FmhoYQg==
  DOCKER_PASSWORD:
    secure: XiHVjf0YM4mciHUdZJ2iJuYbmDzEPnJTjoEsImTkexw=

install:
  - docker version

before_build:
  - docker login -u=%DOCKER_USERNAME% -p=%DOCKER_PASSWORD%

build_script:
  - docker build -t "$env:DOCKER_IMAGE" .

test_script:
  - docker run "$env:DOCKER_IMAGE"

deploy_script:
  - docker push "$env:DOCKER_IMAGE"
