version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_IMAGE: uilianries/conanmsvc14

install:
  - docker version

before_build:
  - docker login -u="$env:DOCKER_USERNAME" -p="$env:DOCKER_PASSWORD"

build_script:
  - docker build -t "$env:DOCKER_IMAGE" .

test_script:
  - docker run "$env:DOCKER_IMAGE"

deploy_script:
  - docker push "$env:DOCKER_IMAGE"
